#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
---
- name: 'Read no_proxy'
  ansible.builtin.shell:
    cmd: "echo $no_proxy"
    executable: /bin/bash
  register: noproxy

- name: 'Set fact'
  ansible.builtin.set_fact:
    cluster_proxy_list: "{{k8s_pod_cidr | default('10.244.0.0/16')}},{{ k8s_service_cidr | default('10.96.0.0/12')}},{{ groups['cluster_hosts'] | map('extract', hostvars, ['ansible_host']) | join(',') }},{{ groups['cluster_hosts'] | map('extract', hostvars, ['private_ip']) | join(',') }},{{ k8s_apiserver_cluster_ip | default('10.96.0.1')}}"

# avoid duplicate append
- name: 'Test cluster proxy list already exists'
  ansible.builtin.shell: grep -F -q '{{ cluster_proxy_list }}' /etc/environment
  register: test_cluster_proxy_list
  ignore_errors: true

- name: 'Add cluster proxy list to no-proxy'
  ansible.builtin.blockinfile:
    path: /etc/environment
    block: |
      no_proxy={{ noproxy.stdout_lines | first | default('') }},{{ cluster_proxy_list }}
  become: true
  when: test_cluster_proxy_list.rc != 0

- name: 'Reset ssh connection'
  ansible.builtin.meta: reset_connection

- name: 'Force all notified handlers to run'
  ansible.builtin.meta: flush_handlers

- name: 'Wait for all host to become reachable'
  failed_when: false
  ansible.builtin.wait_for_connection:
    delay: 10
    timeout: 120
