
dev_cert_conf_dir: /usr/local/etc/wsf/certs
dev_registry_port: 20666
dev_registry_name: dev-registry
dev_registry_mirror: ""
dev_registry_certs_prefix: "Intel"
dev_registry_certs_path:
  ubuntu: /usr/local/share/ca-certificates
  debian: /usr/local/share/ca-certificates
  centos: /etc/pki/ca-trust/source/anchors
  rhel: /etc/pki/ca-trust/source/anchors
