#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: delete namespace
  block:

  - name: delete deployment
    command: "timeout 5m kubectl --namespace={{ wl_namespace }} delete -f /tmp/{{ wl_namespace }}-k8s-script.yaml --ignore-not-found=true --grace-period=150"
    ignore_errors: yes

  - name: get resource types
    shell: "kubectl api-resources --namespaced -o name --no-headers | cut -f1 -d."
    register: resources

  - name: delete resources
    shell:
      cmd: "timeout 5m kubectl --namespace={{ wl_namespace }} delete {{ resources.stdout_lines | join(',') }} --all --ignore-not-found=true --grace-period=150"
      executable: /bin/bash
    ignore_errors: yes

  - name: delete namespace
    command: "timeout 10m kubectl delete namespace {{ wl_namespace }} --grace-period=300 --wait --ignore-not-found=true"
    register: delns
    until: delns.rc == 0
    retries: 10
    delay: 10

  rescue:

  - name: perform kill namespace workaround
    command: "bash -c 'kubectl replace --raw \"/api/v1/namespaces/{{ wl_namespace }}/finalize\" -f <(kubectl get ns {{ wl_namespace }} -o json | grep -v \"\\\"kubernetes\\\"\")'"
    ignore_errors: yes
