
- name: Install emon prerequisites
  apt:
    name: 
      - build-essential
    state: present
  become: yes
  register: aptrc
  until: aptrc is success
  retries: 10
  delay: 10

- name: Detect kernel version
  shell:
    cmd: uname -r
    executable: /bin/bash
  register: kernel_version

- name: Check if kernel header is already installed
  stat:
    path: "/usr/src/kernels/{{ kernel_version.stdout }}"
  register: kernel_header

- name: Install kernel header
  apt:
    name: 
      - "linux-headers-{{ kernel_version.stdout }}"
    state: present
  become: yes
  register: aptrc
  until: aptrc is success
  retries: 10
  delay: 10
  when: not kernel_header.stat.exists

- name: Install emon
  command:  
    cmd: "bash sep-installer.sh -u -C {{ emon_bin_path }} --accept-license -ni -i -g {{ emon_group }}"
    chdir: "{{ emon_src_path }}"
  become: yes

