#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: Check OS
  shell:
    cmd: ". /etc/os-release; echo $ID"
    executable: /bin/bash
  register: os

- name: Remove any changes
  blockinfile:
    marker: "# {mark} WSF Setup"
    path: "{{ cleanup_hugepage_actions[os.stdout]['grub_path'] }}"
    state: absent
  register: grubsts
  ignore_errors: yes

- name: Update grub if updated
  shell: "{{ cleanup_hugepage_actions[os.stdout]['update_grub_cmd'] }}"
  when: grubsts.msg == "Block removed"
  ignore_errors: yes

- name: request reboot
  set_fact:
    cleanup_reboot_required: "{{ cleanup_reboot_required or (grubsts.msg == 'Block removed') }}"

