
- name: Generate out.perf
  shell: "perf script {{ perf_script_options }} -i /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-perf.record > /tmp/{{ wl_namespace }}-{{ trace_node.1 }}-perf.out"
  become: yes
  delegate_to: "{{ trace_node.1 }}"
  ignore_errors: yes

- name: Fetch out.perf
  fetch:
    src: "/tmp/{{ wl_namespace }}-{{ trace_node.1 }}-perf.out"
    dest: "{{ wl_logs_dir }}/{{ trace_node.1 }}-{{ itr | default(1) }}-perf/perf.out"
    flat: yes
  become: yes
  delegate_to: "{{ trace_node.1 }}"
  ignore_errors: yes

- name: Remove any collection file
  file:
    path: "/tmp/{{ wl_namespace }}-{{ trace_node.1 }}-perf.out"
    state: absent
  become: yes
  delegate_to: "{{ trace_node.1 }}"
  ignore_errors: yes

- name: Install perl
  apt:
    name:
    - perl
    update_cache: yes
    state: present
  become: yes
  become_flags: -E
  ignore_errors: yes
  delegate_to: localhost
  register: aptrc
  until: aptrc is success
  retries: 10
  delay: 10

- name: Create flamegraph SVG
  shell: "stackcollapse-perf.pl {{ perf_flamegraph_collapse_options }} {{ wl_logs_dir }}/{{ trace_node.1 }}-{{ itr | default(1) }}-perf/perf.out | flamegraph.pl {{ perf_flamegraph_svg_options }} > {{ wl_logs_dir }}/{{ trace_node.1 }}-{{ itr | default(1) }}-perf/perf.flamegraph.svg"
  become: no
  delegate_to: localhost
  ignore_errors: yes

- name: Remove any collection file
  file:
    path: "{{ wl_logs_dir }}/{{ trace_node.1 }}-{{ itr | default(1) }}-perf/perf.out"
    state: absent
  delegate_to: localhost
  ignore_errors: yes

