# test-config-aws-4xlarge.yaml
# Overwrite the test cases for performance tunning on AWS instances.

*_main:
  SPECJBB_TIER_1_THREADS: 32
  SPECJBB_TIER_2_THREADS: 4
  SPECJBB_TIER_3_THREADS: 8
  SPECJBB_XMX: 16g
  SPECJBB_GROUPS: 1
  AWS_MACHINE_TYPE: m6i.4xlarge