# test-config-aws-8xlarge.yaml
# Overwrite the test cases for performance tunning on AWS instances.

*_main:
  SPECJBB_TIER_1_THREADS: 64
  SPECJBB_TIER_2_THREADS: 5
  SPECJBB_TIER_3_THREADS: 12
  SPECJBB_XMX: 32g
  SPECJBB_GROUPS: 1
  AWS_MACHINE_TYPE: m6i.8xlarge