# test-config-aws-xlarge.yaml
# Overwrite the test cases for performance tunning on AWS instances.

*_main:
  SPECJBB_TIER_1_THREADS: 16
  SPECJBB_TIER_2_THREADS: 2
  SPECJBB_TIER_3_THREADS: 4
  SPECJBB_XMX: 4g
  SPECJBB_GROUPS: 1
  AWS_MACHINE_TYPE: m6i.xlarge