#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

k8s_flannel_version: "v0.18.1"
k8s_flannel_repo: "https://raw.githubusercontent.com/flannel-io/flannel/{{ k8s_flannel_version }}/Documentation/kube-flannel.yml"

