---
# Note: update below variables values as per requirements if needed
# Intel Device Plugin Operator setup
dp_operator_ref: "v0.24.0"
dp_operator_namespace: "inteldeviceplugins-system"

# QAT Device Plugin setup
qat_device_plugin_ver: "0.24.0"
intel_qat_dp_namespace: "inteldeviceplugins-system"
qat_device_plugin_dpdk_drivers: "vfio-pci"
qat_device_plugin_drivers_for_kernel:
  - dh895xccvf
  - c4xxxvf
  - c3xxxvf
  - 4xxxvf
  - c6xxvf
  - d15xxvf
qat_device_plugin_apparmor_profile: "unconfined"
qat_device_plugin_max_vfs: "32"
qat_device_plugin_dir: "/opt/qat_device_plugin"
qat_device_plugin_nodeselector:
  - "intel.feature.node.kubernetes.io/qat=true"
