#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
k8s_nfd_version: "v0.13.2" #  update as required.
k8s_nfd_namespace: "node-feature-discovery"
k8s_nfd_url: "https://github.com/kubernetes-sigs/node-feature-discovery/deployment/overlays/default?ref={{ k8s_nfd_version }}"
k8s_nfd_registry: "registry.k8s.io/nfd"
k8s_enable_nfd: false
