#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

cleanup_restore_path: /usr/local/etc/wsf-restore
cleanup_hugepage_actions:
  "ubuntu":
    grub_path: /etc/default/grub.d/99-wsf-settings.cfg
    update_grub_cmd: |
        update-grub
  "debian":
    grub_path: /etc/default/grub.d/99-wsf-settings.cfg
    update_grub_cmd: |
        update-grub
  "centos":
    grub_path: /etc/default/grub
    update_grub_cmd: |
        grub2-mkconfig -o /boot/grub2/grub.cfg
        grub2-mkconfig -o /etc/grub2.cfg
  "rhel":
    grub_path: /etc/default/grub
    update_grub_cmd: |
        grub2-mkconfig -o /boot/grub2/grub.cfg
        grub2-mkconfig -o /etc/grub2.cfg

  "anolis":
    grub_path: /etc/default/grub
    update_grub_cmd: |
        grub2-mkconfig -o /boot/grub2/grub.cfg
        grub2-mkconfig -o /etc/grub2.cfg

