#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

gprofiler_options: "--profiling-frequency=11 --profiling-duration=2"
gprofiler_version: "1.28.0"
gprofiler_package: "https://github.com/Granulate/gprofiler/releases/download/{{ gprofiler_version }}"

