#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: Install collectd
  apt:
    name: collectd
    update_cache: true
    install_recommends: false
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: yes
  delegate_to: "{{ trace_node.1 }}"
  when: not collectd.stat.exists
  register: aptrc
  until: aptrc is success
  retries: 10
  delay: 10

