#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- block:

  - name: Install epel-release
    yum:
      name:
      - epel-release
    become: yes
    register: yumrc
    until: yumrc is success
    retries: 10
    delay: 10

  - name: Install collectd
    yum:
      name:
      - collectd
      - collectd-disk
      update_cache: true
    become: yes
    register: yumrc
    until: yumrc is success
    retries: 10
    delay: 10

  delegate_to: "{{ trace_node.1 }}"
