#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: Install collectd
  apt:
    name: collectd
    update_cache: true
    install_recommends: false
  when: not collectd.stat.exists
  become: yes
  register: aptrc
  until: aptrc is success
  retries: 10
  delay: 10

- name: set collectd path
  set_fact:
    config_path: /etc/collectd/collectd.conf

- name: Ensure config path exists
  file:
    path: "{{ config_path | dirname }}"
    state: directory
  become: yes

