#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

- name: delete flannel ip links
  command: "ip link delete flannel.1"
  become: true
  ignore_errors: yes

