# test-config-customized.yaml
# Overwrite the workload parameters for performance

*_tcp_*:
  SERVER_CORE_LIST: "0-15"
  CLIENT_CORE_LIST: "0-15"
  PARALLEL_NUM: "16"
  BUFFER_SIZE: "128K"
  SERVER_OPTIONS: ""
  CLIENT_OPTIONS: ""
