apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-dlb-plugin
  labels:
    app: intel-dlb-plugin
spec:
  selector:
    matchLabels:
      app: intel-dlb-plugin
  template:
    metadata:
      labels:
        app: intel-dlb-plugin
    spec:
      containers:
      - name: intel-dlb-plugin
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: intel/intel-dlb-plugin:0.24.0
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        terminationMessagePath: /tmp/termination-log
        volumeMounts:
        - name: devfs
          mountPath: /dev
          readOnly: true
        - name: sysfs
          mountPath: /sys/class/dlb2
          readOnly: true
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: devfs
        hostPath:
          path: /dev
      - name: sysfs
        hostPath:
          path: /sys/class/dlb2
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
      nodeSelector:
        kubernetes.io/arch: amd64